apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: oph5xpjpq-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: artifactory-artifactory-jcr.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap-docker/rhtap-qe:4b1ac55fe8fc82cce15c067ceba608256a43befa@sha256:38adc17ad5224913b4bf0c4a91316ebeab950bdb862e64ffe16c48b0f5446cc2
        name: container-image  
